Calculate the eigenvalues and eigenvectors of the input squared matrix!

In [ ]:
# Solution
import numpy as np
from numpy import linalg as LA

n = int(input('Enter the dimensions of the squared matrix: '))

A = [[int(j) for j in input().split(' ')] for i in range(n)]

values, vectors = LA.eig(A)

print('The eigenvalues are: \n', values)
print('The eigenvectors are: \n', vectors)

Enter the dimensions of the squared matrix: 3


Based on the eigenvalues and eigenvectors, reconstruct the original matrix.

In [17]:
from numpy import diag
from numpy import dot
from numpy.linalg import inv
from numpy import array
from numpy.linalg import eig

print("\nOriginal Matrix:\n", A)

# Calculates eigenvalues and eigenvectors
values, vectors = eig(A)


M = vectors.dot(diag(values)).dot(inv(vectors))

print("Rebuilt Matrix:\n",M)


Original Matrix:
 [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Rebuilt Matrix:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
